### PR TITLE
Clean up server/controller/views/styles

### PR DESCRIPTION
**Pull request by cbrenner04**

### CODE REVIEW

**Comment by cbrenner04** [comment]
@mchlltt @Mtutak this gets handlebars involved, but strictly to cover the requirement as it is exactly the same as the `index.html`. I also removed some of the leftover font stuff and cleaned up the server/controller interaction.

**Comment by mchlltt** [comment]
I'm good with this, except that when I tried to run it, I got an error because we didn't have an index.handlebars file to render.

**Comment by cbrenner04** [comment]
That's weird. It's in there

**Comment by mchlltt** [comment]
Hmm, yeah,, it is. Probably I messed something up, feel free to merge.

**Pull request merged**
